---
title: "case_study"
author: "Mengfan Luo"
date: "23/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
#library(p8105.datasets)
#library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Z scores

```{r}
x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec))/sd(x_vec)

z_scores = function(x) {
  z = (x - mean(x))/sd(x)
  return(z)
}

z_scores(x = x_vec)

```


```{r, error=TRUE}
z_scores(3)
z_scores(c("a","b","c"))
```

Improve:

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x)<3){
    stop("x should have at least 3 numbers")
  }
  
  z = (x - mean(x))/sd(x)
  return(z)
}

```

## Multiple outcomes
Return a output dataframe


```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x)<3){
    stop("x should have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = tibble(
    mean = mean_x,
    sd = sd_x
  )
  
  return(output_df)
}

```


```{r}
mean_and_sd(x_vec)
```


How to debug?

```{r}
# create an x
x = x_vec

#Then can check those inside the function

#Don't forget to remove x
rm(x)

```


## different sample sizes, means and sds

```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 2, sd = 3)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )



```


Functions that simulates data, compute mean and sd

```{r}
sim_mean_sd = function(n, mu = 0, sigma = 1){
  sim_data = tibble(
    x = rnorm(n,mean = mu,sd = sigma)
  )
  
   sim_data %>% 
     summarize(mean = mean(x),
                     sd = sd(x))
}

sim_mean_sd(30)

```


```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


A lot of pages for reviews...

A function that gives reviews based on url

```{r}
get_page_reviews = function(page_url){
  
  page_html = read_html(page_url)

  review_titles = 
    page_html %>%
    html_elements(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    page_html %>%
    html_elements("#cm_cr-review_list .review-rating") %>%
    html_text()
  
  review_text = 
    page_html %>%
    html_elements(".review-text-content span") %>%
    html_text()
  
  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  return(reviews)
}

url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

get_page_reviews(url)


base_url  =  "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

urls = str_c(base_url,1:5)

bind_rows(
  get_page_reviews(urls[1]),
  get_page_reviews(urls[2]),
  get_page_reviews(urls[3]),
  get_page_reviews(urls[4]),
  get_page_reviews(urls[5])
)

```




















